hl.on("hyprland.start", function()
  --hl.exec_cmd("waybar &")
  hl.exec_cmd("qs &")
  --hl.exec_cmd("swaync &")
  hl.exec_cmd("awww-daemon &")
  --hl.exec_cmd("hypridle")
  hl.exec_cmd("systemctl --user start hyprpolkitagent.service &")
  hl.exec_cmd("xsettingsd &")
end)
