
$image = assets/astronaut_jellyfish.jpg
$background = rgba(0f1416ff)

$image = assets/astronaut_jellyfish.jpg
$error = rgba(ffb4abff)

$image = assets/astronaut_jellyfish.jpg
$error_container = rgba(93000aff)

$image = assets/astronaut_jellyfish.jpg
$inverse_on_surface = rgba(2c3133ff)

$image = assets/astronaut_jellyfish.jpg
$inverse_primary = rgba(00687bff)

$image = assets/astronaut_jellyfish.jpg
$inverse_surface = rgba(dee3e6ff)

$image = assets/astronaut_jellyfish.jpg
$on_background = rgba(dee3e6ff)

$image = assets/astronaut_jellyfish.jpg
$on_error = rgba(690005ff)

$image = assets/astronaut_jellyfish.jpg
$on_error_container = rgba(ffdad6ff)

$image = assets/astronaut_jellyfish.jpg
$on_primary = rgba(003641ff)

$image = assets/astronaut_jellyfish.jpg
$on_primary_container = rgba(afecffff)

$image = assets/astronaut_jellyfish.jpg
$on_primary_fixed = rgba(001f27ff)

$image = assets/astronaut_jellyfish.jpg
$on_primary_fixed_variant = rgba(004e5dff)

$image = assets/astronaut_jellyfish.jpg
$on_secondary = rgba(1d343aff)

$image = assets/astronaut_jellyfish.jpg
$on_secondary_container = rgba(cee7efff)

$image = assets/astronaut_jellyfish.jpg
$on_secondary_fixed = rgba(061f25ff)

$image = assets/astronaut_jellyfish.jpg
$on_secondary_fixed_variant = rgba(344a51ff)

$image = assets/astronaut_jellyfish.jpg
$on_surface = rgba(dee3e6ff)

$image = assets/astronaut_jellyfish.jpg
$on_surface_variant = rgba(bfc8cbff)

$image = assets/astronaut_jellyfish.jpg
$on_tertiary = rgba(292e4dff)

$image = assets/astronaut_jellyfish.jpg
$on_tertiary_container = rgba(dee0ffff)

$image = assets/astronaut_jellyfish.jpg
$on_tertiary_fixed = rgba(141937ff)

$image = assets/astronaut_jellyfish.jpg
$on_tertiary_fixed_variant = rgba(404565ff)

$image = assets/astronaut_jellyfish.jpg
$outline = rgba(899295ff)

$image = assets/astronaut_jellyfish.jpg
$outline_variant = rgba(3f484bff)

$image = assets/astronaut_jellyfish.jpg
$primary = rgba(85d2e8ff)

$image = assets/astronaut_jellyfish.jpg
$primary_container = rgba(004e5dff)

$image = assets/astronaut_jellyfish.jpg
$primary_fixed = rgba(afecffff)

$image = assets/astronaut_jellyfish.jpg
$primary_fixed_dim = rgba(85d2e8ff)

$image = assets/astronaut_jellyfish.jpg
$scrim = rgba(000000ff)

$image = assets/astronaut_jellyfish.jpg
$secondary = rgba(b2cbd3ff)

$image = assets/astronaut_jellyfish.jpg
$secondary_container = rgba(344a51ff)

$image = assets/astronaut_jellyfish.jpg
$secondary_fixed = rgba(cee7efff)

$image = assets/astronaut_jellyfish.jpg
$secondary_fixed_dim = rgba(b2cbd3ff)

$image = assets/astronaut_jellyfish.jpg
$shadow = rgba(000000ff)

$image = assets/astronaut_jellyfish.jpg
$source_color = rgba(2a3a3fff)

$image = assets/astronaut_jellyfish.jpg
$surface = rgba(0f1416ff)

$image = assets/astronaut_jellyfish.jpg
$surface_bright = rgba(343a3cff)

$image = assets/astronaut_jellyfish.jpg
$surface_container = rgba(1b2022ff)

$image = assets/astronaut_jellyfish.jpg
$surface_container_high = rgba(252b2dff)

$image = assets/astronaut_jellyfish.jpg
$surface_container_highest = rgba(303638ff)

$image = assets/astronaut_jellyfish.jpg
$surface_container_low = rgba(171c1eff)

$image = assets/astronaut_jellyfish.jpg
$surface_container_lowest = rgba(090f11ff)

$image = assets/astronaut_jellyfish.jpg
$surface_dim = rgba(0f1416ff)

$image = assets/astronaut_jellyfish.jpg
$surface_tint = rgba(85d2e8ff)

$image = assets/astronaut_jellyfish.jpg
$surface_variant = rgba(3f484bff)

$image = assets/astronaut_jellyfish.jpg
$tertiary = rgba(c0c4ebff)

$image = assets/astronaut_jellyfish.jpg
$tertiary_container = rgba(404565ff)

$image = assets/astronaut_jellyfish.jpg
$tertiary_fixed = rgba(dee0ffff)

$image = assets/astronaut_jellyfish.jpg
$tertiary_fixed_dim = rgba(c0c4ebff)

