-- Generated by wallust, do not edit.
-- Consumed by the Lua Hyprland config via require("colors.custom.wallust").
-- bg1 is darker than bg0; bg2..bg4 are derived lighter shades for borders/surfaces.
colors = {
    bg0    = "rgb(292D3E)",
    bg1    = "rgb(1D202B)",
    bg2    = "rgb(3A3E4D)",
    bg3    = "rgb(474A59)",
    bg4    = "rgb(545765)",

    fg     = "rgb(D6DEEB)",

    red    = "rgb(F07178)",
    orange = "rgb(FFCB6B)",
    yellow = "rgb(FFCB6B)",
    green  = "rgb(C3E88D)",
    aqua   = "rgb(89DDFF)",
    blue   = "rgb(82AAFF)",
    purple = "rgb(C792EA)",
    pink   = "rgb(C792EA)",

    grey0  = "rgb(33384D)",
    grey1  = "rgb(33384D)",
    grey2  = "rgb(C7CCD5)",
}
