-- Generated by wallust, do not edit.
-- Consumed by the Lua Hyprland config via require("colors.custom.wallust").
-- bg1 is darker than bg0; bg2..bg4 are derived lighter shades for borders/surfaces.
colors = {
    bg0    = "rgb(1D2021)",
    bg1    = "rgb(141617)",
    bg2    = "rgb(2F3233)",
    bg3    = "rgb(3D3F40)",
    bg4    = "rgb(4A4D4D)",

    fg     = "rgb(D4BE98)",

    red    = "rgb(EA6962)",
    orange = "rgb(D8A657)",
    yellow = "rgb(D8A657)",
    green  = "rgb(A9B665)",
    aqua   = "rgb(89B482)",
    blue   = "rgb(7DAEA3)",
    purple = "rgb(D3869B)",
    pink   = "rgb(D3869B)",

    grey0  = "rgb(1D2021)",
    grey1  = "rgb(1D2021)",
    grey2  = "rgb(A89984)",
}
